# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#51f4fc"
format = '[$user ]($style)'
disabled = false
